using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using SENGENSystem.Server.Common.Auditing;
using SENGENSystem.Server.Common.Persistence;
using SENGENSystem.Server.Domain;

namespace SENGENSystem.Server.Features.Registration.AssignStudentNumber
{
    // Vertical slice: SEN-GEN issues a registration number, but the official *student number* is
    // generated by a separate student-records system. Once a registrant is enrolled there, the
    // Admission Officer looks them up and records that number here (FR-SIS). The School Admin
    // inherits this via the all-roles claims transformation.
    public record AssignStudentNumberRequest(string? StudentNumber);

    public record AssignableRegistrationDto(
        Guid Id,
        string RegistrationNumber,
        string FullName,
        string Program,
        string Status,
        string Email,
        string? OfficialStudentNumber,
        string? OfficialStudentNumberSetAtUtc)
    {
        public static AssignableRegistrationDto From(StudentRegistration r) =>
            new(
                r.Id,
                r.StudentNumber,
                r.FullName,
                r.Program.ToString(),
                r.Status.ToString(),
                r.Email,
                r.OfficialStudentNumber,
                Iso.Utc(r.OfficialStudentNumberSetAtUtc));
    }

    public static class AssignStudentNumberEndpoints
    {
        private const string Policy = nameof(UserRole.AdmissionOfficer);

        public static IEndpointRouteBuilder MapAssignStudentNumber(this IEndpointRouteBuilder app)
        {
            app.MapGet("/api/registration/student-number", ListAsync)
                .RequireAuthorization(p => p.RequireRole(Policy));
            app.MapPost("/api/registration/{id:guid}/student-number", AssignAsync)
                .RequireAuthorization(p => p.RequireRole(Policy));
            return app;
        }

        // Search registrations so the officer can find the enrollee to number. Defaults to those
        // still missing an official student number (the actual work queue); an explicit search
        // widens to any registration, matched on registration number or name.
        private static async Task<IResult> ListAsync(
            string? search,
            bool? unassignedOnly,
            AppDbContext db,
            CancellationToken cancellationToken)
        {
            var query = db.StudentRegistrations.AsNoTracking().AsQueryable();

            if (!string.IsNullOrWhiteSpace(search))
            {
                var term = search.Trim();
                query = query.Where(r =>
                    r.StudentNumber.Contains(term)
                    || r.LastName.Contains(term)
                    || r.FirstName.Contains(term)
                    || (r.OfficialStudentNumber != null && r.OfficialStudentNumber.Contains(term)));
            }
            else if (unassignedOnly ?? true)
            {
                query = query.Where(r => r.OfficialStudentNumber == null);
            }

            var items = await query
                .OrderByDescending(r => r.CreatedAtUtc)
                .Take(500)
                .ToListAsync(cancellationToken);

            return Results.Ok(new
            {
                count = items.Count,
                registrations = items.Select(AssignableRegistrationDto.From).ToList()
            });
        }

        private static async Task<IResult> AssignAsync(
            Guid id,
            AssignStudentNumberRequest request,
            ClaimsPrincipal principal,
            AppDbContext db,
            AuditLog audit,
            CancellationToken cancellationToken)
        {
            var number = request.StudentNumber?.Trim();
            if (string.IsNullOrWhiteSpace(number))
            {
                return Results.ValidationProblem(new Dictionary<string, string[]>
                {
                    ["studentNumber"] = ["The official student number is required."]
                });
            }
            if (number.Length > 30)
            {
                return Results.ValidationProblem(new Dictionary<string, string[]>
                {
                    ["studentNumber"] = ["Student number is too long (max 30 characters)."]
                });
            }

            var registration = await db.StudentRegistrations
                .FirstOrDefaultAsync(r => r.Id == id, cancellationToken);
            if (registration is null)
            {
                return Results.NotFound(new { message = "Registration not found." });
            }

            // The official number is a real-world identity: never let two registrations share one.
            var clash = await db.StudentRegistrations.AnyAsync(
                r => r.Id != id && r.OfficialStudentNumber == number, cancellationToken);
            if (clash)
            {
                return Results.Conflict(new
                {
                    message = $"Student number {number} is already recorded against another registration."
                });
            }

            Guid.TryParse(principal.FindFirstValue(ClaimTypes.NameIdentifier), out var officerId);

            var previous = registration.OfficialStudentNumber;
            registration.OfficialStudentNumber = number;
            registration.OfficialStudentNumberSetAtUtc = DateTime.UtcNow;
            registration.OfficialStudentNumberSetByUserId = officerId == Guid.Empty ? null : officerId;

            audit.Record(AuditAction.StudentNumberAssigned,
                (previous is null
                    ? $"Recorded student number {number} for {registration.FullName} ({registration.StudentNumber})."
                    : $"Updated student number for {registration.FullName} ({registration.StudentNumber}) from {previous} to {number}."),
                "StudentRegistration", registration.Id.ToString());
            await db.SaveChangesAsync(cancellationToken);

            return Results.Ok(AssignableRegistrationDto.From(registration));
        }
    }
}
